spring.application.name=finflow-gateway

spring.datasource.url=jdbc:postgresql://localhost:5432/finflow_gateway
spring.datasource.username=postgres
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=qwertyuiopasdfghjklzxcvbnmmnbvcxzlkjhgfdsapoiuytrewq1234567890
jwt.expiration=900000